#!/usr/bin/env bash

# Fail fast when a command returns non-zero exit code.
set -ev


sdk=${EMULATOR_ANDROID_SDK}
abi=${EMULATOR_ABI}

# Create and start emulator.
echo "Creating emulator device running SDK $sdk on $abi."
echo no | avdmanager create avd --snapchat --sdcard 200M --name "test-$sdk-$abi" --package "system-images;android-$sdk;google_apis;$abi"

echo "Starting emulator device."
# Launch the emulator from the emulator tools directory, in background:
# See: https://www.bram.us/2017/05/12/launching-the-android-emulator-from-the-command-line/
cd $(dirname $(which emulator)) && ./emulator -no-audio -no-window -gpu off -use-system-libs -avd "test-$sdk-$abi" &

# Wait for the emulator to finish initial logging.
sleep 10

adb devices
# Wait for AVD to start.
android-wait-for-emulator "test-$sdk-$abi"


echo "Transferring emulator configuration."
# Turn off animations.
adb shell settings put global window_animation_scale 0 &
adb shell settings put global transition_animation_scale 0 &
adb shell settings put global animator_duration_scale 0 &
# For multi-dex issue on devices API < 19.
adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
adb shell stop installd
adb shell start installd


# Wake up device.
echo "Wake up emulator."
adb shell input keyevent 82 &
