#!/usr/bin/env bash

# Fail fast when a command returns non-zero exit code.
set -ev

# Pass yes ('y') to all interrupts of the SDK manager command.
# Also omit lines containing '=' to avoid exceeding log length limits on CIs, e.g. Travis.
while true; do echo y; done | sdkmanager "$@" | grep -v = || true
