#!/usr/bin/env bash

# Fail fast when a command returns non-zero exit code.
set -ev
CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Setup SDK manager.
${CURRENT_DIR}/android-setup-sdk

# Download SDK tools.
echo "Installing SDK tools."
${CURRENT_DIR}/android-silent-sdkmanager "tools"
echo "Installing build tools $ANDROID_BUILD_TOOLS."
${CURRENT_DIR}/android-silent-sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"
echo "Installing platform tools."
${CURRENT_DIR}/android-silent-sdkmanager "platform-tools"
echo "Installing Android platform SDK $ANDROID_SDK."
${CURRENT_DIR}/android-silent-sdkmanager "platforms;android-$ANDROID_SDK"

# Update component.
${CURRENT_DIR}/android-update-sdk
