#!/usr/bin/env bash

# Fail fast when a command returns non-zero exit code.
set -e

# Setup SDK manager.
android-setup-sdk

# Download SDK tools.
echo "Installing SDK tools."
android-silent-sdkmanager "tools"
echo "Installing build tools $ANDROID_BUILD_TOOLS."
android-silent-sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"
echo "Installing platform tools."
android-silent-sdkmanager "platform-tools"
echo "Installing Android platform SDK $ANDROID_SDK."
android-silent-sdkmanager "platforms;android-$ANDROID_SDK"

# Update component.
android-update-sdk
