#!/usr/bin/env bash

# Fail fast when a command returns non-zero exit code.
set -e
CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

${CURRENT_DIR}/android-install-emulator
${CURRENT_DIR}/android-launch-emulator

# Generate code coverage tests.
echo "Running connected instrumentation tests with Gradle."
./gradlew --daemon --console=plain connectedCheck
# TODO Instead of using `connectedCheck`, run integration tests on multiple devices using Spoon:
#./gradlew --console=plain spoonDebugAndroidTest
