#!/usr/bin/env bash

# Decrypt Google Play publishing key.
openssl aes-256-cbc -K $encrypted_ae7a043411a6_key -iv $encrypted_ae7a043411a6_iv \
    -in api-7281121051860956110-977812-57e7308358e6.json.enc \
    -out secret/api-7281121051860956110-977812-57e7308358e6.json \
    -d

# Fail fast when a command returns non-zero exit code.
set -e

SDK_DOWNLOAD_URL="https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"


# Fix missing config file.
mkdir -p ~/.android
touch ~/.android/repositories.cfg


# Download and unzip Android SDK tools (if not already cached)
# Latest version available here: https://developer.android.com/studio/#command-tools
SDK_DOWNLOAD_DIR="$ANDROID_HOME/dl"
SDK_DOWNLOAD_ZIP="$SDK_DOWNLOAD_DIR/sdk-tools.zip"
mkdir -p ${SDK_DOWNLOAD_DIR}
if test ! -e ${SDK_DOWNLOAD_ZIP}
then
    echo "Fetching SDK tools from $SDK_DOWNLOAD_URL."
    curl ${SDK_DOWNLOAD_URL} > ${SDK_DOWNLOAD_ZIP}
else
    echo "Skipped download. Archive already exists."
fi
echo "Unzipping $SDK_DOWNLOAD_ZIP."
unzip -qq -n ${SDK_DOWNLOAD_ZIP} -d ${ANDROID_HOME}


# Download SDK tools.
echo "Installing SDK tools."
android-silent-sdkmanager "tools"
echo "Installing build tools $ANDROID_BUILD_TOOLS."
android-silent-sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"
echo "Installing platform tools."
android-silent-sdkmanager "platform-tools"
echo "Installing Android platform SDK $ANDROID_SDK."
android-silent-sdkmanager "platforms;android-$ANDROID_SDK"

android-update-sdk
