#!/bin/bash
# Copied from https://github.com/travis-ci/travis-cookbooks/blob/precise-stable/ci_environment/android-sdk/files/default/android-wait-for-emulator which is released under the MIT license.

# Fail fast when a command returns non-zero exit code.
set -e

BOOT_ANIMATION=""
FAIL_COUNTER=0
TIMEOUT_IN_SECONDS=360

echo "Waiting for emulator to start..."
until [[ "$BOOT_ANIMATION" =~ "stopped" ]]
do
    BOOT_ANIMATION=`adb -e shell getprop init.svc.bootanim 2>&1 &`
    echo ${BOOT_ANIMATION}
    if [[ "$BOOT_ANIMATION" =~ "device not found" || "$BOOT_ANIMATION" =~ "device offline"
        || "$BOOT_ANIMATION" =~ "running" || "$BOOT_ANIMATION" =~ "error: no emulators found" ]]
    then
        FAIL_COUNTER=$((FAIL_COUNTER + 1))
        echo "Still waiting ($FAIL_COUNTER seconds)..."
        if [[ ${FAIL_COUNTER} -gt ${TIMEOUT_IN_SECONDS} ]]
        then
            echo "Timeout ($TIMEOUT_IN_SECONDS seconds) reached. Failed to start emulator."
            exit 1
        fi
    elif  [[ "$BOOT_ANIMATION" =~ "stopped" ]]
    then
        echo "Emulator is ready."
    else
        echo "Cannot get device status." 1>&2
        exit -1
    fi
    sleep 1
done
