#!/usr/bin/env bash

# Fail fast when a command returns non-zero exit code.
set -e

echo "Create new GitHub draft release, including a changelog and app bundles."
./gradlew --daemon --console=plain githubRelease
