#!/usr/bin/env bash

# Fail fast when a command returns non-zero exit code.
set -e
CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd secret

echo "Create archive with all secret files."
tar -cf secrets.tar --exclude=secrets.tar --exclude=secrets.tar.enc --exclude-vcs ./

echo "Encrypt files, store keys on Travis CI and save the decryption command."
decrypt_line=$(travis encrypt-file -f -p secrets.tar \
    | sed 's/^ *//;s/ *$//' \
    | grep -E '^openssl')

echo "Save decryption command to decryption script."
sed -i "s/^openssl.*$/$decrypt_line/g" "$CURRENT_DIR/decrypt-secrets"