#!/usr/bin/env bash

# Print executed commands; fail fast when a command returns non-zero exit code.
set -ev

# Download and unzip Android SDK tools (if not already cached)
# Latest version available here: https://developer.android.com/studio/#command-tools
SDK_DOWNLOAD_DIR="$ANDROID_HOME/tmp/dl"
mkdir -p ${SDK_DOWNLOAD_DIR}
if test ! -e "$SDK_DOWNLOAD_DIR/sdk-tools.zip"
then
    curl "https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip" > "$SDK_DOWNLOAD_DIR/sdk-tools.zip"
fi
unzip -qq -n "$SDK_DOWNLOAD_DIR/sdk-tools.zip" -d ${ANDROID_HOME}


# Download SDK tools.
silent-sdkmanager "tools"
silent-sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"
silent-sdkmanager "platform-tools"
silent-sdkmanager "platforms;android-$ANDROID_SDK"

update-sdk
