#!/usr/bin/env bash

# Download and unzip Android SDK tools (if not already cached)
# Latest version available here: https://developer.android.com/studio/#command-tools
SDK_DOWNLOAD_DIR="$ANDROID_HOME/tmp/dl"
mkdir -p ${SDK_DOWNLOAD_DIR}
if test ! -e "$SDK_DOWNLOAD_DIR/sdk-tools.zip"
then
    curl "https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip" > "$SDK_DOWNLOAD_DIR/sdk-tools.zip"
fi
unzip -qq -n "$SDK_DOWNLOAD_DIR/sdk-tools.zip" -d ${ANDROID_HOME}


CI_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Download SDK tools.
${CI_SCRIPT_DIR}/silent-sdkmanager "tools"
${CI_SCRIPT_DIR}/silent-sdkmanager "build-tools;$BUILD_TOOLS"
${CI_SCRIPT_DIR}/silent-sdkmanager "platform-tools"
${CI_SCRIPT_DIR}/silent-sdkmanager "platforms;android-$ANDROID_SDK"

${CI_SCRIPT_DIR}/update-sdk
