#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Download SDK tools.
yes | sdkmanager "tools"
yes | sdkmanager "build-tools;$BUILD_TOOLS"
yes | sdkmanager "platform-tools"
yes | sdkmanager "platforms;android-$ANDROID_SDK"

${DIR}/update-sdk
