#!/usr/bin/env bash

# Print executed commands; fail fast when a command returns non-zero exit code.
set -ev

sdk=${EMULATOR_ANDROID_SDK}
abi=${EMULATOR_ABI}

# Create and start emulator.
echo no | avdmanager create avd \
    --force -c 200M -n "test-$sdk-$abi" -k "system-images;android-$sdk;default;$abi"
emulator -avd "test-$sdk-$abi" -no-audio -no-window &

# Wait for AVD to start.
android-wait-for-emulator

# Turn off animations.
adb shell settings put global window_animation_scale 0 &
adb shell settings put global transition_animation_scale 0 &
adb shell settings put global animator_duration_scale 0 &

# For multi-dex issue on devices API < 19.
adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
adb shell stop installd
adb shell start installd

# Wake up device.
adb shell input keyevent 82 &
