#!/usr/bin/env bash

sdk=${EMULATOR_ANDROID_SDK}
abi=${EMULATOR_ABI}

# Create and start emulator.
echo no | ${ANDROID_HOME}/tools/bin/avdmanager create avd \
    --force -c 200M -n "test-$sdk-$abi" -k "system-images;android-$sdk;default;$abi"
${ANDROID_HOME}/emulator/emulator -avd "test-$sdk-$abi" -no-audio -no-window &

# Wait for AVD to start.
android-wait-for-emulator

# Turn off animations.
${ANDROID_HOME}/platform-tools/adb shell settings put global window_animation_scale 0 &
${ANDROID_HOME}/platform-tools/adb shell settings put global transition_animation_scale 0 &
${ANDROID_HOME}/platform-tools/adb shell settings put global animator_duration_scale 0 &

# For multi-dex issue on devices API < 19.
${ANDROID_HOME}/platform-tools/adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
${ANDROID_HOME}/platform-tools/adb shell stop installd
${ANDROID_HOME}/platform-tools/adb shell start installd

# Wake up device.
${ANDROID_HOME}/platform-tools/adb shell input keyevent 82 &
