#!/usr/bin/env bash

# Print executed commands; fail fast when a command returns non-zero exit code.
set -ev

# Set up code coverage report
./gradlew --console=plain jacocoTestReport

# Upload code coverage report
curl -s https://codecov.io/bash | bash -
