#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Update SDK dependencies.
${DIR}/silent-sdkmanager --update
# Accept licenses.
${DIR}/silent-sdkmanager --licenses
