#!/usr/bin/env bash

# Print executed commands; fail fast when a command returns non-zero exit code.
set -ev

# Update SDK dependencies.
silent-sdkmanager --update
# Accept licenses.
silent-sdkmanager --licenses
