name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: macos-10.15
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v7
      - name: "🧰 Install JDK"
        uses: actions/setup-java@v5.6.0
        with:
          java-version: 1.8
          java-package: jdk
      - name: "🧰 Install Android SDK"
        uses: android-actions/setup-android@v4
      - name: "🕶 Decrypt secret files"
        run: |
          cd secret
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.FILES_PASSPHRASE }}" --output secrets.tar secrets.tar.gpg
          tar -xf secrets.tar
      - name: "📁 Copy local CI properties"
        run: cp ci/local.properties ./
      - name: "🏗 Build"
        run: ./gradlew assembleDebug
      - name: "🚀 GitHub release"
        run: ./gradlew githubRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "🚀 Google Play publish"
        run: ./gradlew publishRelease
